### ISSUE TITLE
Testing exclude/include

### ISSUE THREAD

**Issue by liamcoatman** [tomcatling/black-nb#25]
I don't think `test_include_exclude`, `test_empty_include`, `test_empty_exclude` are testing the CLI.

**Comment by tomcatling** [comment]
:( i think you are correct

**Comment by liamcoatman** [comment]
Shall we just delete these tests for now?

**Comment by tomcatling** [comment]
Yes i think so, better to focus on testing the added functionality like keeping any trailing ';' and dealing with ipython magic
