### ISSUE TITLE
use as jupyter presave hook

### ISSUE THREAD

**Issue by hatemhosny** [tomcatling/black-nb#43]
is there any guidance for using black-nb as a presave hook in jupyterlab?

it would be great if that can be automated by running a command or script

thank you

**Comment by MarcoGorelli** [comment]
what's a presave hook?

**Comment by liamcoatman** [comment]
With `black` now supporting notebooks out of the box, we are not adding new features to this project.

If you want to do this yourself, it looks like you could modify [this](https://jupyter-notebook.readthedocs.io/en/stable/extending/savehooks.html#examples) example by passing the contents of the cell to the [format_cell_source](https://github.com/tomcatling/black-nb/blob/master/black_nb/cli.py#L339) function in `black-nb`.
