### ISSUE TITLE
Deal with `?` IPython syntax

### ISSUE THREAD

**Issue by liamcoatman** [tomcatling/black-nb#53]
A line like `np.sum?` is valid in a Jupyter notebook, and prints the documentation for `np.sum`. Currently `black-nb` will fail to format a cell with lines like this. We need to fix this.

**Comment by MarcoGorelli** [comment]
@liamcoatman in case it's useful to you, `nbqa` handles such cells (currently it'll ignore the line with `np.sum?`, but it will reformat the rest of the cell)
